### ISSUE TITLE
Installation Fail

### ISSUE THREAD

**Issue by cecilialee** [MarkEdmondson1234/gentelellaShiny#1]
Hi! The package seems promising and I'd like to try it out. 
However, I've encountered installation error by running `devtools::install_github("MarkEdmondson1234/gentelellaShiny")`

```
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  namespace ‘httpuv’ 1.3.6.2 is being loaded, but >= 1.4.3 is required
ERROR: lazy loading failed for package ‘gentelellaShiny’
* removing ‘/Users/cecilialee/Library/R/3.4/library/gentelellaShiny’
Installation failed: Command failed (1)
```

**Comment by MarkEdmondson1234** [comment]
Please try installing the newest httpuv first, restart R then try again.

**Comment by cecilialee** [comment]
I've updated the httpuv package and it now works! Thanks!

**Comment by MarkEdmondson1234** [comment]
Will update description so minimum requirements reflect above.

**Comment by bagayogo** [comment]
I am trying to install gentelellaShiny with the following code.
devtools::install_github("MarkEdmondson1234/gentelellaShiny")

However, I encounter the following error message.
Error: Failed to install 'unknown package' from GitHub:
 Timeout was reached: Connection timed out after 10000 milliseconds

Thank you in advance for your response.
