### ISSUE TITLE
Need to double click on sidebar tabs to navigate

### ISSUE THREAD

**Issue by nchelaru** [MarkEdmondson1234/gentelellaShiny#13]
Hello!

First of all, thank you so much for making such a great package!

I have made a [Shiny dashboard](https://nancy-chelaru-centea.shinyapps.io/assn_rules_mining/) using this package, and somehow I need to double click on the sidebar tabs in order to navigate. 

This does seem to be a bug since the sidebar tabs of the demo dashboard made using the code on the Github page works with single clicks. 

Another user has referenced this in issue #10 . 

Thank you very much again!

**Comment by MarkEdmondson1234** [comment]
Thanks for using the package!

The dashboard CSS in general assumes you will have a nested menu at the side there, so the first click is to open it up and the second to choose your option - if you have no options underneath then it will need two clicks.  Can you change the menu so it has the options nested underneath? e.g.

```r
...
sideBarElement(" Home ",
                 icon = icon("home"),
                 list(a(href="index.html", "Dashboard"),
                      a(href="index2.html", "Dashboard2"),
                      a(href="index3.html", "Dashboard3"))                        
  ),
...
```

**Comment by MarkEdmondson1234** [comment]
Or you could try wrapping the entire element in `a()` but untested.

**Comment by nchelaru** [comment]
Thank you so much for your reply! 

Unfortunately, neither the nested options or `a()` wrapping options worked for me.  I tinkered for a bit, and found that the single-click navigation work again when I added the back the `sidebarDate()` element to the sidebar. 

So this issue is solved and I will close it. 

Thank you for all your help again!
