### ISSUE TITLE
tabItem vs datatableoutput

### ISSUE THREAD

**Issue by anujbajracharya** [MarkEdmondson1234/gentelellaShiny#18]
Hi Mark, thanks again for this wonderful package. I have been using it for personal for more than two years now, and I am still simply loving it.

I am facing a very strange problem. I am not sure if it is the issue with the "tabItem" itself or there is something else with other  packages.

I am seeing a very strange behavior in my aws ec2 instance (ubuntu 18.04). Below is your sample code that i tested.
I added DT::dataTableOutput("tbl_cars") (below in bold.) to see if i can output the datable instead of the dist_plot. 

Problem: "tbl_cars" is not showing in the output when I put DT::dataTableOutput("tbl_cars") INSIDE tabItem. But when I remove that tabItem, then i see the "tbl_cars". The strange thing is that I am not seeing the same behavior in my home server which runs the same version of shiny, gentelellashiny and r.

I have spent hours in here but no able to figure out what the real root cause here is.
Let me know if this has nothing to do with gentelellashiny. Thanks always Mark.

a section of ui.R
--------------------------
tabItems(
        tabItem(
          tabName = "tab1",
          fluidRow(
            column(
              width = 4,
              align = "center",
              sliderInput(
                "obs",
                "Number of observations:",
                min = 0,
                max = 1000,
                value = 500
              )
            ),
            column(
              width = 8,
              align = "center",
              **DT::dataTableOutput("tbl_cars")**
              # plotOutput("distPlot")
            )
          )
        )
        ,
        tabItem(
          tabName = "tab2",
          jumbotron(
            title = "Hello, world!",
            "This is a simple hero unit, a simple jumbotron-style
        component for calling extra attention to featured
        content or information."
          )
        )
      )

a section of server.R
------------------------------
output$tbl_cars <- DT::renderDataTable({
      DT::datatable(mtcars)
    })

my sessioninfo()
-------------------------------
R version 3.6.3 (2020-02-29)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.5 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

locale:
 [1] LC_CTYPE=C.UTF-8       LC_NUMERIC=C           LC_TIME=C.UTF-8        LC_COLLATE=C.UTF-8     LC_MONETARY=C.UTF-8    LC_MESSAGES=C.UTF-8   
 [7] LC_PAPER=C.UTF-8       LC_NAME=C              LC_ADDRESS=C           LC_TELEPHONE=C         LC_MEASUREMENT=C.UTF-8 LC_IDENTIFICATION=C   

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] gentelellaShiny_0.1.0 shiny_1.3.2          

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.7        digest_0.6.28     later_1.3.0       mime_0.12         R6_2.5.1          jsonlite_1.7.2    xtable_1.8-4     
 [8] magrittr_2.0.1    rlang_0.4.11      promises_1.2.0.1  jquerylib_0.1.4   bslib_0.3.1       DT_0.19           shinyjs_2.0.0    
[15] tools_3.6.3       htmlwidgets_1.5.4 crosstalk_1.1.1   yaml_2.2.1        httpuv_1.6.3      fastmap_1.1.0     compiler_3.6.3   
[22] htmltools_0.5.2   sass_0.4.0

**Comment by MarkEdmondson1234** [comment]
Thanks for writing!

I can't say for sure, but sometimes in the past I think the JavaScript libraries for DataTable clash with the Genetella libraries or something, and causes tables not to be displayed.  You could try to see in your browser console if you get any error messages to see if it is the root cause.   Perhaps your server is running a different version of the JS libraries involved?  Check for any differences in JS libraries and R libraries.

**Comment by anujbajracharya** [comment]
Thanks for the quick reply. I was investigating with "shinydashboard", where it showed the datatable as expected. But somehow, I am not able to show the same table in gentelellashiny.

When I inspected the "Network" tab of the browser between these two behavior, I clearly see two jQuery files missing when the table is not displayed.

jquery.datatables.extra.css
jquery.datatables.min.css

Do you think it has anything to do with the datatable not displaying?

**Comment by MarkEdmondson1234** [comment]
Yes that sounds like a good suspect - the data table GitHub issues would be best place to investigate - feel free to link to here from there for background info. This library is pretty old since it's last update now so perhaps it's a compatibility issue.

**Comment by anujbajracharya** [comment]
Thanks. I close this for now.
