### ISSUE TITLE
Icon within gentelellasidebar is not displaying

### ISSUE THREAD

**Issue by anujbajracharya** [MarkEdmondson1234/gentelellaShiny#5]
First of all, thanks for the awesome bootstrap theme.
I am experiencing a problem of icon not displaying in the gentelellasidebar.

1. `sidebarItem("Boxes", tabName = "boxes", icon = icon("bar-chart"))`
2. `sidebarItem("Tabs", tabName = "tabs", icon = "bar-chart"),`

The first one gives a BLANK before "Boxes".
Second one gives a SQUARE-like icon before "Boxes".

But, I am able to set_title like below where the 'icon' part is working well.
`site_title = shiny::HTML(paste(shiny::icon("bar-chart"), "Dashboard")),`

Am I missing anything here?

**Comment by DivadNojnarg** [comment]
Hi,

This is due to the new shiny 1.2 update. Please download gentelellaShiny from here 
https://github.com/RinteRface/gentelellaShiny

I will do a pull request in this repo ASAP

**Comment by anujbajracharya** [comment]
Thanks. But if you meant that I should install the gentelellashiny as below, then I had done exactly the same in the beginning. 

devtools::install_github("MarkEdmondson1234/gentelellaShiny")

But let remove the package and install it once again.

**Comment by DivadNojnarg** [comment]
The PR is ready:

```r
devtools::install_github("MarkEdmondson1234/gentelellaShiny")
```

Let me know

**Comment by anujbajracharya** [comment]
Works great. Thank you.

**Comment by Friedrichz** [comment]
On a related topic: 

Is there any chance to customize the Gentelella Icon ("Paw") alongside the title in the top left corner of the Sidebar inside the R code?

Thank you!

**Comment by uttam-1996** [comment]
the issue is still the same can you please fix it

**Comment by DivadNojnarg** [comment]
What version of shiny are you currently using?
